import React, { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import api from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { toast } from "sonner";
import { motion } from "framer-motion";
import { Sparkles, ChevronDown } from "lucide-react";
import {
  Accordion, AccordionContent, AccordionItem, AccordionTrigger,
} from "@/components/ui/accordion";

const ALL_TYPES = ["technical", "behavioral", "hr", "coding", "project"];

export default function Interview() {
  const location = useLocation();
  const [resumes, setResumes] = useState([]);
  const [analyses, setAnalyses] = useState([]);
  const [role, setRole] = useState("Software Engineer");
  const [difficulty, setDifficulty] = useState("medium");
  const [selectedTypes, setSelectedTypes] = useState(["technical", "behavioral", "hr"]);
  const [count, setCount] = useState(3);
  const [resumeId, setResumeId] = useState("");
  const [analysisId, setAnalysisId] = useState(location.state?.analysis_id || "");
  const [loading, setLoading] = useState(false);
  const [set, setSet] = useState(null);
  const [history, setHistory] = useState([]);

  const loadAll = async () => {
    try {
      const [r, a, hist] = await Promise.all([
        api.get("/resume"),
        api.get("/analyses"),
        api.get("/interview-sets"),
      ]);
      setResumes(r.data);
      setAnalyses(a.data);
      setHistory(hist.data);
      if (!resumeId && r.data.length > 0) setResumeId(r.data[0].id);
    } catch { /* ignore */ }
  };

  useEffect(() => { loadAll(); }, []); // eslint-disable-line

  const toggleType = (t) => {
    setSelectedTypes((prev) => prev.includes(t) ? prev.filter((x) => x !== t) : [...prev, t]);
  };

  const generate = async () => {
    if (selectedTypes.length === 0) return toast.error("Select at least one question type");
    setLoading(true);
    setSet(null);
    try {
      const payload = {
        role,
        difficulty,
        types: selectedTypes,
        count_per_type: count,
        resume_id: resumeId || undefined,
        analysis_id: analysisId || undefined,
      };
      const { data } = await api.post("/generate-interview", payload);
      setSet(data);
      toast.success(`Generated ${data.questions?.length || 0} questions`);
      loadAll();
    } catch (err) {
      toast.error(err?.response?.data?.detail || "Generation failed");
    } finally {
      setLoading(false);
    }
  };

  const groupedQuestions = React.useMemo(() => {
    if (!set?.questions) return {};
    return set.questions.reduce((acc, q) => {
      const t = q.type || "other";
      acc[t] = acc[t] || [];
      acc[t].push(q);
      return acc;
    }, {});
  }, [set]);

  return (
    <div className="space-y-8" data-testid="interview-root">
      <div>
        <div className="text-xs uppercase tracking-[0.2em] text-blue-300 font-bold">AI Coach</div>
        <h1 className="font-display text-4xl sm:text-5xl font-extrabold tracking-tighter mt-2">Interview kit</h1>
        <p className="text-gray-400 mt-2">Tailored questions with model answers, generated by Gemini.</p>
      </div>

      <div className="panel p-6">
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
          <div>
            <Label className="text-xs uppercase tracking-[0.15em] text-gray-400">Role</Label>
            <Input
              value={role}
              onChange={(e) => setRole(e.target.value)}
              className="mt-2 bg-black/20 border-white/10 h-11 rounded-xl focus:border-blue-500"
              data-testid="input-role"
            />
          </div>
          <div>
            <Label className="text-xs uppercase tracking-[0.15em] text-gray-400">Difficulty</Label>
            <Select value={difficulty} onValueChange={setDifficulty}>
              <SelectTrigger className="mt-2 bg-black/20 border-white/10 h-11 rounded-xl" data-testid="select-difficulty">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="bg-[#11141d] border-white/10 text-white">
                <SelectItem value="easy">Easy</SelectItem>
                <SelectItem value="medium">Medium</SelectItem>
                <SelectItem value="hard">Hard</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label className="text-xs uppercase tracking-[0.15em] text-gray-400">Per type</Label>
            <Input
              type="number"
              min={1}
              max={10}
              value={count}
              onChange={(e) => setCount(parseInt(e.target.value || "3", 10))}
              className="mt-2 bg-black/20 border-white/10 h-11 rounded-xl focus:border-blue-500"
              data-testid="input-count"
            />
          </div>
          <div>
            <Label className="text-xs uppercase tracking-[0.15em] text-gray-400">Use resume</Label>
            <Select value={resumeId} onValueChange={setResumeId}>
              <SelectTrigger className="mt-2 bg-black/20 border-white/10 h-11 rounded-xl" data-testid="select-resume">
                <SelectValue placeholder="Pick a resume" />
              </SelectTrigger>
              <SelectContent className="bg-[#11141d] border-white/10 text-white">
                {resumes.length === 0 && <div className="px-3 py-2 text-sm text-gray-500">No resumes</div>}
                {resumes.map((r) => <SelectItem key={r.id} value={r.id}>{r.filename}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="mt-6">
          <Label className="text-xs uppercase tracking-[0.15em] text-gray-400">Question types</Label>
          <div className="flex flex-wrap gap-2 mt-2">
            {ALL_TYPES.map((t) => (
              <button
                key={t}
                onClick={() => toggleType(t)}
                data-testid={`chip-type-${t}`}
                className={`px-4 py-2 rounded-full text-sm capitalize transition-colors ${
                  selectedTypes.includes(t)
                    ? "bg-blue-500/20 text-blue-200 border border-blue-500/40"
                    : "bg-white/[0.05] text-gray-400 border border-white/10 hover:bg-white/[0.1]"
                }`}
              >
                {t}
              </button>
            ))}
          </div>
        </div>

        <div className="mt-6 flex flex-wrap items-center gap-3">
          <Label className="text-xs uppercase tracking-[0.15em] text-gray-400 mr-2">JD from analysis (optional)</Label>
          <Select value={analysisId} onValueChange={setAnalysisId}>
            <SelectTrigger className="bg-black/20 border-white/10 h-11 rounded-xl min-w-[240px]" data-testid="select-analysis">
              <SelectValue placeholder="None" />
            </SelectTrigger>
            <SelectContent className="bg-[#11141d] border-white/10 text-white">
              {analyses.length === 0 && <div className="px-3 py-2 text-sm text-gray-500">No analyses</div>}
              {analyses.map((a) => <SelectItem key={a.id} value={a.id}>{a.jd_title}</SelectItem>)}
            </SelectContent>
          </Select>
          <Button
            onClick={generate}
            disabled={loading}
            className="bg-blue-600 hover:bg-blue-500 rounded-full px-6 h-11 ml-auto"
            data-testid="btn-generate-questions"
          >
            {loading ? "Generating…" : (<><Sparkles className="w-4 h-4 mr-2" /> Generate questions</>)}
          </Button>
        </div>
      </div>

      {loading && (
        <div className="panel p-8 flex items-center gap-4">
          <div className="w-8 h-8 rounded-full border-2 border-blue-500 border-t-transparent animate-spin" />
          <div>
            <div className="font-display font-bold">Gemini is thinking…</div>
            <div className="text-sm text-gray-500">Usually takes 5-15 seconds.</div>
          </div>
        </div>
      )}

      {set && !loading && (
        <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="panel p-6" data-testid="questions-result">
          <div className="flex items-center justify-between mb-4">
            <div>
              <div className="text-[10px] uppercase tracking-[0.2em] text-gray-500 font-bold">Result</div>
              <div className="font-display font-bold text-xl">{set.role} · <span className="capitalize">{set.difficulty}</span></div>
            </div>
            <div className="text-xs text-gray-500">{set.questions.length} questions</div>
          </div>

          {Object.entries(groupedQuestions).map(([type, qs]) => (
            <div key={type} className="mt-4">
              <div className="text-[10px] uppercase tracking-[0.2em] text-blue-300 font-bold mb-2">{type} ({qs.length})</div>
              <Accordion type="single" collapsible>
                {qs.map((q, i) => (
                  <AccordionItem key={i} value={`${type}-${i}`} className="border-white/[0.05]">
                    <AccordionTrigger className="text-left hover:no-underline" data-testid={`q-${type}-${i}`}>
                      <span className="text-sm font-medium">{q.question}</span>
                    </AccordionTrigger>
                    <AccordionContent className="text-sm text-gray-300 leading-relaxed">
                      <div className="text-[10px] uppercase tracking-[0.2em] text-gray-500 font-bold mb-1">Model answer</div>
                      {q.model_answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>
          ))}
        </motion.div>
      )}

      {history.length > 0 && (
        <div className="panel p-6">
          <div className="font-display font-bold text-lg mb-3">Recent sets</div>
          <div className="space-y-2">
            {history.slice(0, 5).map((s) => (
              <button
                key={s.id}
                onClick={() => setSet(s)}
                className="w-full flex items-center gap-3 p-3 rounded-lg bg-white/[0.02] border border-white/[0.05] hover:bg-white/[0.05] text-left transition-colors"
                data-testid={`history-set-${s.id}`}
              >
                <div className="w-10 h-10 rounded-lg bg-blue-500/10 grid place-items-center text-blue-300 font-bold text-xs uppercase">
                  {s.difficulty[0]}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-sm font-medium truncate">{s.role} · <span className="capitalize">{s.difficulty}</span></div>
                  <div className="text-xs text-gray-500">{s.questions.length} qs • {s.created_at.slice(0, 10)}</div>
                </div>
                <ChevronDown className="w-4 h-4 text-gray-500" />
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
